import Restaurant from "../types/restaurant";

const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '2',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '3',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '4',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '5',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '6',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '7',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '8',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '9',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '10',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '11',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '12',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '13',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '14',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '15',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '16',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
  {
    id: '17',
    image: 'https://via.placeholder.com/150',
    name: 'Kenjiro',
    cuisine: 'Japan',
    budget: 2,
    rating: 4,
  },
];

export default RESTAURANTS;